# Site settings
title: Huy Quang Pham - Character Design, Hobbyist Artist
email: huypq104@gmail.com
phone: +841213866888
description: > # this means to ignore newlines until "url:"
  Sketching, drawing and painting clear my head from sad & sorrow. Life is not easy but with god.
url: "http://huyquangpham.com" # the base hostname & protocol for your site
imgOg: "/og.jpg"
author: Huy Quang Pham
github_username: huyquangpham
exclude: [vender]

# Plugins

# Conversion
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Markdown Processors
kramdown:
  input: GFM
